server:
  port: 8090
  
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
#      - id: user-service
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/user-service/**

      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/login
        - Method=POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/user-service/(?<segment>.*), /$\{segment}
      
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/users
        - Method=POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/actuator/**
        - Method=GET, POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        
      - id: user-service
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user-service/**
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/user-service/(?<segment>.*), /$\{segment}
#        - AuthenticationFilter

        
      - id: catalog-service
        uri: lb://CATALOG-SERVICE
        predicates:
        - Path=/catalog-service/**
        
      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/order-service/**
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
#token:
# secret: secretToken
      
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace
      