server:
  port: 8088
  
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file://C:/Users/sure0/OneDrive/바탕 화면/WorkSpaces/ecommerce-git/ecommerce/git-local-repo